"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Import credentials from separate config file
try:
    from .credentials import SECRET_KEY, DATABASE, EMAIL, AWS, GCP, JWT, ADMIN
except ImportError:
    raise ImportError(
        "credentials.py not found! Please copy credentials.example.py to credentials.py "
        "and fill in your actual credentials."
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Secret key is now imported from credentials.py
# SECRET_KEY is imported above

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('DEBUG', 'True') == 'True'
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "35.200.133.126",
    "192.168.1.2",
    "rstpfe.storage.googleapis.com",
    "cctvapi.suvidhaen.com",
    "13.233.78.193",  # Added as per instruction
    "cctv.suvidhaen.com",
]



FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')





INSTALLED_APPS = [
    # Admin theme (add before django.contrib.admin)
    'jazzmin',  # Modern admin interface
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'django_object_actions',
    'apps.admin.apps.CustomAdminConfig',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',  # Swagger documentation for DRF
    
    # Local apps
    'apps.mailer', 
    'apps.users',  # Users app
    'apps.cctv',   # CCTV camera management
    
    
    # Additional admin tools
    'django_admin_logs',  # Enhanced admin logging
    'ninja',  # We'll use Django Ninja which is FastAPI-like framework for Django
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Should be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, './templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Database credentials are now imported from credentials.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DATABASE['NAME'],
        'USER': DATABASE['USER'],
        'PASSWORD': DATABASE['PASSWORD'],
        'HOST': DATABASE['HOST'],
        'PORT': DATABASE['PORT'],
    }
}


APPEND_SLASH = False

#Mailer Settings - Now using credentials from credentials.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = EMAIL['HOST']
EMAIL_PORT = EMAIL['PORT']
EMAIL_USE_TLS = EMAIL['USE_TLS']
EMAIL_USE_SSL = EMAIL['USE_SSL']
EMAIL_HOST_USER = EMAIL['HOST_USER']
EMAIL_HOST_PASSWORD = EMAIL['HOST_PASSWORD']
DEFAULT_FROM_EMAIL = EMAIL['DEFAULT_FROM']

# OTP specific email settings
OTP_EMAIL_FROM = 'noreply@yourdomain.com'

# Email accounts configuration for different purposes
EMAIL_ACCOUNTS = {
    'no-reply': {
        'email': 'noreply@yourdomain.com',
        'display_name': 'Shree Swami Smartha System'
    },
    'team': {
        'email': 'team@yourdomain.com',
        'display_name': 'Shree Swami Smartha Team'
    },
    'invitation': {
        'email': 'invitation@yourdomain.com',
        'display_name': 'Shree Swami Smartha Invitations'
    }
}



# IMAP settings for incoming mail
IMAP_HOST = 'imap.gmail.com'  # Fixed the typo
IMAP_PORT = 993  # Standard IMAP SSL port
IMAP_USE_SSL = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us';
TIME_ZONE = 'Asia/Kolkata';
USE_I18N = True;
USE_TZ = True;


# Custom User Model
AUTH_USER_MODEL = 'users.User'  # Assuming your custom User model is in the users app


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ================================
# Cloud Storage Configuration
# ================================
# Choose storage backend: 'GCP' or 'AWS' or 'BOTH'
CLOUD_STORAGE_BACKEND = 'AWS'  # Default to AWS

# ================================
# AWS S3 Storage Configuration
# ================================
# AWS Credentials - Now using credentials from credentials.py
AWS_ACCESS_KEY_ID = AWS['ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = AWS['SECRET_ACCESS_KEY']
AWS_SESSION_TOKEN = AWS['SESSION_TOKEN']
AWS_REGION_NAME = AWS['REGION_NAME']

# S3 Bucket Settings
AWS_STORAGE_BUCKET_NAME = AWS['STORAGE_BUCKET_NAME']
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_REGION_NAME}.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache for 1 day
}

# S3 Storage Behavior Settings
AWS_S3_FILE_OVERWRITE = False        # Don't overwrite files with same name
AWS_DEFAULT_ACL = 'private'          # Keep files private by default
AWS_S3_VERIFY = True                 # Verify SSL certificates
AWS_S3_USE_SSL = True                # Use HTTPS
AWS_QUERYSTRING_AUTH = True          # Use signed URLs for private files
AWS_S3_SIGNATURE_VERSION = 's3v4'    # Use signature version 4

# Storage Behavior Settings
AWS_STORAGE_CLEANUP_LOCAL = True     # Clean up local files after successful upload
AWS_STORAGE_AUTO_UPLOAD = True       # Automatically upload new recordings
AWS_STORAGE_UPLOAD_TIMEOUT = 600     # Upload timeout in seconds (10 minutes)
AWS_STORAGE_RETRY_ATTEMPTS = 3       # Number of retry attempts for failed uploads

# S3 URLs
AWS_S3_BASE_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}"
AWS_S3_MEDIA_URL = f"{AWS_S3_BASE_URL}/media/"

# S3 Signed URL Settings
AWS_PRESIGNED_URL_EXPIRATION = 7200  # Default expiration time for presigned URLs (in seconds, 2 hours)

# S3 Storage Paths
AWS_LOCATION = 'recordings'          # Base folder in bucket for recordings
AWS_MEDIA_LOCATION = 'media'         # Folder for media files

# ================================
# GCP Cloud Storage Configuration (Legacy/Backup)
# ================================
# Main GCP Storage Settings - Now using credentials from credentials.py
GCP_STORAGE_BUCKET_NAME = GCP['STORAGE_BUCKET_NAME']
GCP_STORAGE_PROJECT_ID = GCP['STORAGE_PROJECT_ID']
GCP_STORAGE_CREDENTIALS_PATH = GCP['STORAGE_CREDENTIALS_PATH']
GCP_STORAGE_USE_GCS = GCP['STORAGE_USE_GCS']

# GCP Storage Behavior Settings
GCP_STORAGE_CLEANUP_LOCAL = True     # Clean up local files after successful GCP upload
GCP_STORAGE_AUTO_UPLOAD = True       # Automatically upload new recordings to GCP
GCP_STORAGE_UPLOAD_TIMEOUT = 600     # Upload timeout in seconds (10 minutes)
GCP_STORAGE_RETRY_ATTEMPTS = 3       # Number of retry attempts for failed uploads

# GCP Storage URLs
GCP_STORAGE_BASE_URL = f"https://storage.googleapis.com/{GCP_STORAGE_BUCKET_NAME}"
GCP_STORAGE_MEDIA_URL = f"{GCP_STORAGE_BASE_URL}/media/"

# GCP Signed URL Settings
GCP_SIGNED_URL_EXPIRATION = 120      # Default expiration time for signed URLs (in minutes)
GCP_SIGNED_URL_VERSION = 'v4'        # Use v4 signing for better compatibility

# CORS settings - Enhanced for mobile and web support
CORS_ALLOW_ALL_ORIGINS = True if DEBUG else False  # Only allow all origins in development

# Always allow credentials for authentication
CORS_ALLOW_CREDENTIALS = True

# Comprehensive list of allowed origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://localhost:5174",  # Vite dev server for admin project
    "http://localhost:3000",  # React dev server
    "http://192.168.1.2:5173",  # Vite dev server on IP
    "http://192.168.1.2:8000",  # Backend on IP
    "http://192.168.1.2:3000",  # React dev server on IP
    "http://192.168.1.2",
    "https://192.168.1.1",
    # Google storage
    "https://rstpfe.storage.googleapis.com",
    "http://rstpfe.storage.googleapis.com",
    # Mobile app origins
    "capacitor://localhost",
    "ionic://localhost",
    "http://localhost",
    "https://localhost",
    "http://35.200.133.126",
    "http://35.200.133.126:8000",

    "http://13.233.78.193",  # Added as per instruction
    "https://cctv.suvidhaen.com",
    
    FRONTEND_URL,  # Using the FRONTEND_URL from environment variables
]

# Allow all necessary HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'HEAD',  # Add HEAD method
]

# Comprehensive headers list for mobile and web support
CORS_ALLOW_HEADERS = [
    # Standard headers
    'accept',
    'accept-encoding',
    'accept-language',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'x-request-id',
    'x-request-time',
    
    # Custom headers for platform identification
    'x-requested-platform',  # Allow the platform identification header
    'x-capacitor-platform',  # Allow Capacitor platform header for mobile apps
    
    # Additional mobile app headers
    'x-ionic-platform',
    'x-app-version',
    'x-device-id',
    
    # Common API headers
    'cache-control',
    'pragma',
    'expires',
    'x-forwarded-for',
    'x-real-ip',
    
    # Security headers
    'x-frame-options',
    'x-content-type-options',
    'referrer-policy',
]

# Headers to expose to the client
CORS_EXPOSE_HEADERS = [
    'Content-Type', 
    'X-CSRFToken',
    'Authorization',
    'X-Request-ID',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
]

# Preflight cache time (24 hours)
CORS_PREFLIGHT_MAX_AGE = 86400

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.users.auth.JWTAuthentication',  # Our custom JWT authentication
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
};

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField';


# Custom JWT Token Settings - Now using credentials from credentials.py
CUSTOM_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Access token expires in 1 day
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Refresh token expires in 30 days
    'ALGORITHM': JWT['ALGORITHM'],
    'SIGNING_KEY': JWT['SECRET_KEY'],
}

# Django Ninja Settings
NINJA_JWT = True
NINJA_JWT_HEADER = "Authorization"
NINJA_JWT_HEADER_PREFIX = "Bearer"
NINJA_PAGINATION_CLASS = "ninja.pagination.PageNumberPagination"
NINJA_PAGINATION_PER_PAGE = 10
NINJA_MAX_PER_PAGE_SIZE = 100
NINJA_MAX_LIMIT = 1000
NINJA_NUM_PROXIES = 1
NINJA_DEFAULT_THROTTLE_RATES = {
    "anon": "100/hour",
    "user": "1000/hour",
}
NINJA_FIX_REQUEST_FILES_METHODS = ["POST", "PUT", "PATCH"]

# Jazzmin Settings (Admin Theme Configuration)
JAZZMIN_SETTINGS = {
    # General settings
    "site_title": "Admin",
    "site_header": "",
    "site_brand": "",
    "welcome_sign": "Welcome to the Admin Panel",
    "copyright": " Ltd",
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site", "url": "/"}, 
        {"model": "auth.User"},
    ],
    
    # UI Customization
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    
    # Theme
    "dark_mode_theme": "darkly",
    
    # Custom Links
    "custom_links": {
        "users": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["auth.view_user"]
        }]
    },
    
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Admin Site Configuration
ADMIN_SITE_HEADER = "Your Project Administration"
ADMIN_SITE_TITLE = "Your Project Admin Portal"
ADMIN_INDEX_TITLE = "Welcome to Your Project Admin"

# Admin Security Settings - Now using credentials from credentials.py
ADMIN_URL = ADMIN['URL']  # Custom admin URL
ADMIN_HONEYPOT = True  # Enable fake admin login page
ADMIN_HONEYPOT_EMAIL_ADMINS = True  # Send email on failed login attempts

# Admin Email Settings
ADMINS = [
    (ADMIN['NAME'], ADMIN['EMAIL']),
]
MANAGERS = ADMINS

# Admin logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/debug.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Django Import-Export Settings
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False

# Update the logo URL to use the media path
LOGO_URL = os.getenv('LOGO_URL', '/public/logo.png')

# CSRF Configuration
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost',
    "http://192.168.1.2",
    "http://35.200.133.126:8000",
    "http://35.200.133.126",
    "https://rstpfe.storage.googleapis.com",
    "http://rstpfe.storage.googleapis.com",
    "http://13.233.78.193",  # Added as per instruction
    "https://cctv.suvidhaen.com",
]
CSRF_COOKIE_SECURE = False  # Set to False in development if not using HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to the cookie
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie instead of session

# Add CSRF middleware if not already present
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Make sure this is included
    'corsheaders.middleware.CorsMiddleware',  # Should be at the top
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configure CORS if you're using it
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

