# Generated by Django 5.1.5 on 2025-08-09 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Camera name/label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Camera description', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Camera IP address')),
                ('port', models.PositiveIntegerField(default=554, help_text='RTSP port (usually 554)')),
                ('username', models.CharField(blank=True, help_text='Camera username', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='Camera password', max_length=100, null=True)),
                ('rtsp_url', models.URLField(help_text='Full RTSP URL (e.g., rtsp://admin:password@192.168.1.100:554/stream1)', max_length=500)),
                ('rtsp_url_sub', models.URLField(blank=True, help_text='Secondary RTSP stream URL (lower quality)', max_length=500, null=True)),
                ('camera_type', models.CharField(choices=[('ip', 'IP Camera'), ('rtsp', 'RTSP Camera'), ('webcam', 'Webcam')], default='rtsp', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='inactive', max_length=15)),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=255, null=True)),
                ('auto_record', models.BooleanField(default=False, help_text='Enable automatic recording')),
                ('record_quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('max_recording_hours', models.PositiveIntegerField(default=24, help_text='Maximum hours to keep recordings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time camera was online', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='cctv.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Schedule name', max_length=255)),
                ('schedule_type', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('continuous', 'Continuous')], default='once', max_length=15)),
                ('start_time', models.TimeField(help_text='Recording start time')),
                ('end_time', models.TimeField(help_text='Recording end time')),
                ('start_date', models.DateField(blank=True, help_text='Start date (for one-time schedules)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date', null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text="List of days for weekly schedules (e.g., ['monday', 'friday'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cctv.camera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording Schedule',
                'verbose_name_plural': 'Recording Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Recording name/description', max_length=255)),
                ('file_path', models.CharField(help_text='Path to recording file', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('duration', models.DurationField(blank=True, help_text='Recording duration', null=True)),
                ('start_time', models.DateTimeField(help_text='Recording start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Recording end time', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='scheduled', max_length=15)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1920x1080', max_length=20, null=True)),
                ('frame_rate', models.PositiveIntegerField(blank=True, help_text='FPS', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cctv.camera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='cctv.recordingschedule')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CameraAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('control', 'View & Control'), ('admin', 'Full Admin')], default='view', max_length=10)),
                ('can_record', models.BooleanField(default=False, help_text='Can start/stop recordings')),
                ('can_schedule', models.BooleanField(default=False, help_text='Can create/modify schedules')),
                ('can_download', models.BooleanField(default=True, help_text='Can download recordings')),
                ('access_start_time', models.TimeField(blank=True, help_text='Daily access start time', null=True)),
                ('access_end_time', models.TimeField(blank=True, help_text='Daily access end time', null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='cctv.camera')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_camera_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Access',
                'verbose_name_plural': 'Camera Accesses',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'camera')},
            },
        ),
    ]
