# Generated by Django 5.1.3 on 2025-08-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='codec',
            field=models.CharField(blank=True, help_text='Video codec used (e.g., H264)', max_length=10, null=True),
        ),
    ]
