# Generated by Django 5.1.3 on 2025-08-30 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_add_camera_access_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this camera', related_name='accessible_cameras', through='cctv.CameraAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this camera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cameras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cameraaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_camera_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='user',
            field=models.ForeignKey(help_text='User who is viewing the live stream', on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recording',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated this recording', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordingschedule',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='recording_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
