# Generated by Django 5.1.5 on 2025-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_camera_assigned_users_alter_camera_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rtsp_path',
            field=models.CharField(blank=True, help_text='Custom RTSP path (e.g., /live/0/SUB, /stream1, /cam/realmonitor)', max_length=200, null=True),
        ),
    ]
