# Generated by Django 4.2.24 on 2025-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_add_rtsp_path_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether camera is currently online'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='Whether camera is currently streaming'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(help_text='Full RTSP URL (e.g., rtsp://admin:password@192.168.1.100:554/stream1)', max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url_sub',
            field=models.CharField(blank=True, help_text='Secondary RTSP stream URL (lower quality)', max_length=500, null=True),
        ),
    ]
