# Generated by Django 4.2.24 on 2025-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_add_streaming_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('gcp', 'Google Cloud Storage')], default='local', help_text='Where the recording file is stored', max_length=10),
        ),
    ]
