# Generated by Django 4.2.25 on 2025-10-28 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0008_gcpvideotransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='recording_mode',
            field=models.CharField(choices=[('backend', 'Backend Recording'), ('local_client', 'Local Client Recording')], default='backend', help_text='Where recordings should be performed', max_length=15),
        ),
        migrations.AddField(
            model_name='recording',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('completed', 'Upload Completed'), ('failed', 'Upload Failed')], default='pending', help_text='Status of GCP upload', max_length=15),
        ),
        migrations.CreateModel(
            name='LocalRecordingClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client system name/location', max_length=255)),
                ('client_token', models.CharField(help_text='Authentication token for this client', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last known IP address', null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp', null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', help_text='Current client status', max_length=10)),
                ('system_info', models.JSONField(blank=True, default=dict, help_text='System information (CPU, RAM, disk space, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cameras', models.ManyToManyField(blank=True, help_text='Cameras assigned to this client for recording', related_name='recording_clients', to='cctv.camera')),
            ],
            options={
                'verbose_name': 'Local Recording Client',
                'verbose_name_plural': 'Local Recording Clients',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='recorded_by_client',
            field=models.ForeignKey(blank=True, help_text='Local client that recorded this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='cctv.localrecordingclient'),
        ),
    ]
