# Generated by Django 4.2.25 on 2025-11-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0009_camera_recording_mode_recording_upload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('aws', 'AWS S3 Storage'), ('gcp', 'Google Cloud Storage')], default='local', help_text='Where the recording file is stored', max_length=10),
        ),
    ]
